### PR TITLE
cmake static lib test (ci.yml)

### PR DESCRIPTION
**Pull request by t-mat**
This PR is follow-up for #1281.
To check #1269, this PR adds actual static library build test for cmake.

note: before merging #1281, this PR fails to build the static library.

https://github.com/t-mat/lz4/actions/runs/6453785476/job/17518007581#step:4:106

```
/usr/bin/ld: CMakeFiles/lz4cli.dir/home/runner/work/lz4/lz4/programs/bench.c.o: in function `BMK_benchMem':
bench.c:(.text+0x1c66): undefined reference to `XXH64'
/usr/bin/ld: bench.c:(.text+0x298a): undefined reference to `XXH64'
collect2: error: ld returned 1 exit status
```

### CODE REVIEW

**Comment by Cyan4973** [comment]
And therefore, it fails since #1281 is not yet merged. Nice !

**Review by Cyan4973 — APPROVED** [review]

**Comment by Cyan4973** [comment]
I was expecting this test to work fine on `dev` since #1281 is merged there,
but apparently it's not ?
`dev` branch is red on this new test, as well as all new PRs.

```
CMake Error at CMakeLists.txt:6 (find_package):
  Could not find a package configuration file provided by "lz4" with any of
  the following names:

    lz4Config.cmake
    lz4-config.cmake

  Add the installation prefix of "lz4" to CMAKE_PREFIX_PATH or set "lz4_DIR"
  to a directory containing one of the above files.  If "lz4" provides a
  separate development package or SDK, be sure it has been installed.
  ```

File: .github/workflows/ci.yml [hunk 1]
```diff
@@ -679,6 +679,24 @@ jobs:
...
+
+    - name: Environment info
+      run: |
+        echo && type cmake && which cmake && cmake --version
+        echo && type make && which make && make -v
+
+    - name: cmake (static lib)
+      run: |
+        CFLAGS=-Werror cmake -S build/cmake -B build -D CMAKE_INSTALL_PREFIX=install_test_dir -DBUILD_STATIC_LIBS=ON
+        VERBOSE=1 cmake --build build
```
Comment (t-mat) [inline .github/workflows/ci.yml:696]: This line must be

```
VERBOSE=1 cmake --build build --target install
```

Without this change, the following cmake test fails to find cmake configuration files.

**Comment by t-mat** [comment]
Sorry!  #1292 fixes this issue.

**Comment by Cyan4973** [comment]
Great !
